# Generated by Django 4.2.5 on 2023-09-27 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatterprofile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatterprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
